# knit .Rmd to .R to run whole pipeline from .sh script.
library(knitr)
#purl("main_model.Rmd", output = "main_model.R", documentation = 2)
#purl("prior_sensitivity.Rmd", output = "prior_sensitivity.R", documentation = 2)
#purl("updating_checks.Rmd", output = "updating_checks.R", documentation = 2)
#purl("likelihood_comparison.Rmd", output = "likelihood_comparison.R", documentation = 2)
#purl("pp_checks.Rmd", output = "pp_checks.R", documentation = 2)
#purl("hyp_testing.Rmd", output = "hyp_testing.R", documentation = 2)
purl("explore_priors.Rmd", output = "explore_priors.R", documentation = 2)
#purl("simulate_predict.Rmd", output = "simulate_predict.R", documentation = 2)